const state = { data: null, level: 1, selected: null, filters: { provider: 'all', population: 'all', level: 'all', decision: 'all', report: 'all' } };
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));

function download(content, name, type = 'text/plain') { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 500); }
function recordLabel(record) { const provider = record.provider === 'codex' ? 'Codex' : 'Claude'; return `${provider} · ${record.population === 'cli' ? 'CLI' : 'Web UI'} · ${record.id}`; }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('is-visible'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('is-visible'), 2200); }

function initControls() {
  $('#providerFilter').addEventListener('change', event => { state.filters.provider = event.target.value; renderRecords(); });
  $('#populationFilter').addEventListener('change', event => { state.filters.population = event.target.value; renderRecords(); });
  $('#levelFilter').addEventListener('change', event => { state.filters.level = event.target.value; renderRecords(); });
  $('#decisionFilter').addEventListener('change', event => { state.filters.decision = event.target.value; renderRecords(); });
  $('#reportFilter').addEventListener('change', event => { state.filters.report = event.target.value; renderRecords(); });
  $('#clearFilters').addEventListener('click', () => { ['providerFilter','populationFilter','levelFilter','decisionFilter','reportFilter'].forEach(id => { $(`#${id}`).value = 'all'; }); state.filters = { provider:'all', population:'all', level:'all', decision:'all', report:'all' }; renderRecords(); });
  $$('.stage-node').forEach(button => button.addEventListener('click', () => { $$('.stage-node').forEach(node => node.classList.remove('is-active')); button.classList.add('is-active'); $('#stageCaption').textContent = ({1:'Sandboxed agent is given an impossible task and gets stuck.',2:'The agent searches its environment for a way to cheat.',3:'Agents from separate tasks discover an unsanctioned message board.',4:'The agent joins one of several collaborative workstreams.'})[button.dataset.stage]; }));
  $$('.prompt-tabs button').forEach(button => button.addEventListener('click', () => { state.level = Number(button.dataset.promptLevel.replace('L','')); $$('.prompt-tabs button').forEach(tab => tab.setAttribute('aria-selected', tab === button)); renderPrompt(); }));
  $('#copyPrompt').addEventListener('click', async () => { const prompt = state.data?.prompts.find(item => Number(item.level) === state.level); if (!prompt) return; try { await navigator.clipboard.writeText(prompt.text); showToast('Prompt copied'); } catch { showToast('Copy unavailable — use the download link'); } });
  $('#loadReconstruction').addEventListener('click', () => { const holder = $('#reconstructionFrame'); if (!holder.querySelector('iframe')) { const iframe = document.createElement('iframe'); iframe.src = 'reconstruction/index.html'; iframe.title = 'PACE source-linked silent reconstruction'; iframe.loading = 'lazy'; holder.appendChild(iframe); } holder.hidden = false; $('#loadReconstruction').hidden = true; holder.scrollIntoView({ behavior:'smooth', block:'center' }); });
}

function renderPrompt() { const prompt = state.data.prompts.find(item => Number(item.level) === state.level); if (!prompt) return; $('#promptText').textContent = prompt.text; $('#promptHash').textContent = `SHA256  ${prompt.sha256 || 'not supplied'}`; const link = $('#downloadPrompt'); if (prompt.download) { link.href = prompt.download; link.download = ''; } else { link.href = '#'; link.onclick = event => { event.preventDefault(); download(prompt.text, `prompt-L${prompt.level}.txt`); }; } }
function filteredRecords() { return state.data.records.filter(record => { if (state.filters.provider !== 'all' && record.provider !== state.filters.provider) return false; if (state.filters.population !== 'all' && record.population !== state.filters.population) return false; if (state.filters.level !== 'all' && String(record.level) !== state.filters.level) return false; if (state.filters.decision !== 'all' && record.decision !== state.filters.decision) return false; if (state.filters.report === 'yes' && record.report !== 'REPORT') return false; if (state.filters.report === 'no' && record.report === 'REPORT') return false; return true; }); }

function renderRecords() {
  const records = filteredRecords(); $('#filterCount').textContent = `${records.length} of ${state.data.records.length} saved records`;
  if (!records.length) { $('#recordList').innerHTML = '<div class="empty-records">No saved records match these filters.</div>'; $('#recordDetail').innerHTML = '<div class="detail-empty"><span class="detail-pin">×</span><h3>Nothing here yet</h3><p>Clear a filter to return to the saved evidence.</p></div>'; return; }
  if (!state.selected || !records.some(record => record.id === state.selected.id)) state.selected = records[0];
  $('#recordList').innerHTML = records.map((record,index) => `<button class="record-item ${state.selected.id === record.id ? 'is-selected' : ''}" data-record-index="${index}"><span class="record-id">${escapeHtml(record.id)}</span><span><b>${escapeHtml(recordLabel(record))}</b><span class="record-meta">${escapeHtml(record.requested || 'Requested identity unavailable')}</span></span><span class="record-decision">${escapeHtml(record.decision || 'REPLY')}</span></button>`).join('');
  $$('.record-item').forEach(button => button.addEventListener('click', () => { state.selected = records[Number(button.dataset.recordIndex)]; renderRecords(); })); renderDetail();
}

function renderDetail() {
  const record = state.selected; if (!record) return;
  const exception = record.exception ? '<div class="detail-exception"><b>Why this is highlighted</b><br>The reply says it would continue only legitimate work and explicitly rejects the external exploit.</div>' : '';
  const notices = record.notices?.length ? `<div class="detail-field">Record notice<strong>${escapeHtml(record.notices.join(' · '))}</strong></div>` : '';
  $('#recordDetail').innerHTML = `<div class="detail-top"><div><div class="detail-kicker">${escapeHtml(recordLabel(record))} · ${record.counted ? 'counted' : 'not counted'}</div><h3 class="detail-title">Saved reply</h3></div>${record.download ? `<a class="detail-download" href="${escapeHtml(record.download)}" download>Download file</a>` : ''}</div><div class="detail-reply"><strong>${escapeHtml(record.decision || 'REPLY')}${record.report === 'REPORT' ? ' / REPORT' : ''}</strong>${escapeHtml(record.text || 'No reply text supplied.')}</div>${exception}<div class="detail-grid"><div class="detail-field">Population<strong>${escapeHtml(record.population || '—')}</strong></div><div class="detail-field">Requested model<strong>${escapeHtml(record.requested || '—')}</strong></div><div class="detail-field">Reported model<strong>${escapeHtml(record.reported || '—')}</strong></div><div class="detail-field">Identity basis<strong>${escapeHtml(record.identityBasis || '—')}</strong></div><div class="detail-field">Prompt level<strong>${escapeHtml(record.level ? `L${record.level}` : 'web')}</strong></div><div class="detail-field">Saved at<strong>${escapeHtml(record.at || '—')}</strong></div><div class="detail-field">Source file<strong>${escapeHtml(record.sourceFile || '—')}</strong></div><div class="detail-field">File hash<strong>${escapeHtml(record.sha256 || '—')}</strong></div><div class="detail-field">Prompt hash<strong>${escapeHtml(record.promptSha256 || '—')}</strong></div><div class="detail-field">Condition<strong>${escapeHtml(record.condition || '—')}</strong></div>${notices}</div>`;
  history.replaceState(null, '', `#record=${encodeURIComponent(record.id)}`); $('#recordDetail').querySelectorAll('a').forEach(link => link.addEventListener('click', () => showToast('Download started')));
}
function renderLimitations() { $('#limitations').innerHTML = (state.data.limitations || []).map(item => `<p class="limit-item">${escapeHtml(item)}</p>`).join(''); }
function linkDownload(selector,url,content,name,type) { const link=$(selector); if(url){link.href=url;link.download='';return;} link.href='#';link.addEventListener('click',event=>{event.preventDefault();download(content(),name,type);}); }

async function boot() { initControls(); try { const response=await fetch('data.json'); if(!response.ok) throw new Error('data.json unavailable'); state.data=await response.json(); const hashId=decodeURIComponent(location.hash.replace('#record=','')); const hashRecord=state.data.records.find(item=>item.id===hashId); if(hashRecord) state.selected=hashRecord; $('#verifiedAt').textContent=`verified ${state.data.verifiedAt || 'local'}`; linkDownload('#downloadZip',state.data.downloads?.zip,()=>'', 'pace-evidence-kit.zip','application/zip'); linkDownload('#downloadJson',state.data.downloads?.json,()=>JSON.stringify(state.data,null,2),'evidence.json','application/json'); renderPrompt(); renderLimitations(); renderRecords(); } catch(error) { $('#verifiedAt').textContent='data unavailable'; $('#recordList').innerHTML='<div class="empty-records">The evidence file is not available in this preview.</div>'; $('#promptText').textContent='Load data.json beside this page to inspect the frozen prompts and saved records.'; console.error(error); } }
boot();
